# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OS POSITIVOS
email: comix@ospositivos.com
description: >- # this means to ignore newlines until "baseurl:"
  fanzine do contra com cultura: uma outra cena de banda desenhada desalinhada desdenhada de propaganda punk veggie anti-nazi com humor & depressão q/b
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ospositivos.pt" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:month/:title:output_ext
twitter_username: ospositivos
github_username:  ospositivos

# Google Analytics
google_analytics: UA-8547796-14

# Build settings
markdown: kramdown
theme: minima
livereload: true

#plugins:
#  - jekyll-feed

# compress_html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

# compress_sass
sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
